lib/newton_web/router.ex
defmodule NewtonWeb.Router do
  use NewtonWeb, :router
  use Pow.Phoenix.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {NewtonWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :auth do
    plug :do_auth
  end

  defp do_auth(conn, _opts) do
    username = System.fetch_env!("AUTH_USERNAME")
    password = System.fetch_env!("AUTH_PASSWORD")
    Plug.BasicAuth.basic_auth(conn, username: username, password: password)
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/" do
    pipe_through :browser

    get "/", NewtonWeb.PageController, :index

    pow_routes()
  end

  scope "/", NewtonWeb do
    pipe_through :browser
    pipe_through :auth

    live "/stats", StatsLive

    # # Class CRUD
    # live "/classes", ClassLive.Index, :index
    # live "/classes/new", ClassLive.Index, :new
    # live "/classes/:id/edit", ClassLive.Index, :edit
    # live "/classes/:id", ClassLive.Show, :show
    # live "/classes/:id/show/edit", ClassLive.Show, :edit

    # # User CRUD
    # live "/users", UserLive.Index, :index
    # live "/users/new", UserLive.Index, :new
    # live "/users/:id/edit", UserLive.Index, :edit
    # live "/users/:id", UserLive.Show, :show
    # live "/users/:id/show/edit", UserLive.Show, :edit

    # Question CRUD
    live "/questions", QuestionLive.Index, :index
    live "/questions/new", QuestionLive.Index, :new
    live "/questions/:id/edit", QuestionLive.Index, :edit
    live "/questions/:id", QuestionLive.Show, :show
    live "/questions/:id/show/edit", QuestionLive.Show, :edit

    # Exam CRUD
    get "/exams/download", DownloadController, :download

    live "/exams", ExamLive.Index, :index
    live "/exams/new", ExamLive.Index, :new
    live "/exams/:id/edit", ExamLive.Index, :edit
    live "/exams/:id", ExamLive.Show, :show
    live "/exams/:id/show/edit", ExamLive.Show, :edit

    live "/exams/:id/edit-questions", ExamLive.EditQuestions, :index
    live "/exams/:id/edit-questions/:question_id/edit", ExamLive.EditQuestions, :edit

    # Comment CRUD
    live "/comments", CommentLive.Index, :index
    live "/comments/new", CommentLive.Index, :new
    live "/comments/:id/edit", CommentLive.Index, :edit
    live "/comments/:id", CommentLive.Show, :show
    live "/comments/:id/show/edit", CommentLive.Show, :edit

    # Tag CRUD
    live "/tags", TagLive.Index, :index
    live "/tags/new", TagLive.Index, :new
    live "/tags/:id/edit", TagLive.Index, :edit
    live "/tags/:id", TagLive.Show, :show
    live "/tags/:id/show/edit", TagLive.Show, :edit

    # Answer CRUD
    live "/answers", AnswerLive.Index, :index
    live "/answers/new", AnswerLive.Index, :new
    live "/answers/:id/edit", AnswerLive.Index, :edit
    live "/answers/:id", AnswerLive.Show, :show
    live "/answers/:id/show/edit", AnswerLive.Show, :edit
  end

  # Other scopes may use custom stacks.
  # scope "/api", NewtonWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: NewtonWeb.Telemetry
    end
  end
end

lib/newton_web/views/layout_view.ex
defmodule NewtonWeb.LayoutView do
  use NewtonWeb, :view
end

lib/newton_web/templates/layout/app.html.eex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/newton_web/templates/layout/live.html.leex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/newton_web/templates/layout/live_navbar.html.leex
<%# -*- mode: web -*- %>
<header>
  <section>
    <nav class="navbar navbar-expand-lg navbar-dark bg-gradient-dark">
      <a class="navbar-brand" href="#" alt="But we really know it was Leibniz who did the cool calculus first.">Newton</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <!-- <li class="nav-item active"> -->
          <!--   <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a> -->
          <!-- </li> -->
          <li class="nav-item">
            <%= link "Questions", to: Routes.question_index_path(@socket, :index), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link "Exams", to: Routes.exam_index_path(@socket, :index), class: "nav-link" %>
          </li>
          <li class="nav-item">
              <%= link "Stats", to: "/stats", class: "nav-link" %>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
          <li class="nav-item"><%= link "LiveDashboard", to: Routes.live_dashboard_path(@socket, :home), class: "nav-link" %></li>
          <% end %>
        </ul>
      </div>
    </nav>
  </section>
</header>

<!-- Toast container -->
<!-- <div aria-live="polite" aria-atomic="true" style="position: relative; min-height: 200px; margin-bottom: -200px"> -->
<!--     <\!-- Position it -\-> -->
<!--     <div style="position: absolute; top: 0; right: 0;"> -->

<!--         <div class="toast" role="alert" aria-live="assertive" aria-atomic="true"> -->
<!--             <div class="toast-header"> -->
<!--                 <\!-- <img src="..." class="rounded mr-2" alt="..."> -\-> -->
<!--                 <strong class="mr-auto">Newton</strong> -->
<!--                 <small class="text-muted">informative</small> -->
<!--                 <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close" phx-click="lv:clear-flash" phx-value-key="info"> -->
<!--                     <span aria-hidden="true">&times;</span> -->
<!--                 </button> -->
<!--             </div> -->
<!--             <div class="toast-body"> -->
<!--                 <%= live_flash(@flash, :info) %> -->
<!--             </div> -->
<!--         </div> -->

<!--     </div> -->
<!-- </div> -->


<main role="main" class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/newton_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Newton", suffix: " · Newton" %>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <%= @inner_content %>
  </body>
</html>